sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7
services:
  - postgresql

env:
  - DATABASE_HOST=localhost
before_script:
  - psql -f ./db/container-files/docker-entrypoint-initdb.d/db.sql -U postgres
  - cd ./app
  - composer install
