sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7
matrix:
  allow_failures:
    - php: hhvm
services:
  - postgresql

env:
  - ENV=travis
before_script:
  - psql -f ./db/container-files/docker-entrypoint-initdb.d/db.sql -U postgres
  - cd ./app
  - composer install
