db:
  image: ihsw/pho-sho-db

base:
  image: ihsw/pho-sho
  environment:
    - DATABASE_HOST=Db
test-base:
  extends:
    service: base
  command: ./bin/run-tests

test:
  extends:
    service: test-base
  links:
    - db:Db
test-dev:
  extends:
    service: test-base
  volumes:
    - ./app:/srv/app
  links:
    - db:Db
