base:
  image: ihsw/pho-sho
web-test:
  extends:
    service: base
web:
  extends:
    service: base
  ports:
    - 80:80
test:
  extends:
    service: base
  command: phpunit
test-dev:
  extends:
    service: test
  volumes:
    - ./app:/srv/app
